<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="awojtowicz" name="ru.stqa.pft.addressbook.test.NewContactCreation" tests="1" failures="1" timestamp="08 sie 2018 17:07:59 GMT" time="12.942" errors="0">
  <testcase name="testNewContactCreation" time="12.942" classname="ru.stqa.pft.addressbook.test.NewContactCreation">
    <failure type="java.lang.AssertionError" message="Lists differ at element [8]: ContactData{id=&#039;43&#039;, name=&#039;Jezierska Hanna +483453845&#039;} != ContactData{id=&#039;2147483647&#039;, name=&#039;Hanna&#039;} expected [ContactData{id=&#039;43&#039;, name=&#039;Jezierska Hanna +483453845&#039;}] but found [ContactData{id=&#039;2147483647&#039;, name=&#039;Hanna&#039;}]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [8]: ContactData{id='43', name='Jezierska Hanna +483453845'} != ContactData{id='2147483647', name='Hanna'} expected [ContactData{id='43', name='Jezierska Hanna +483453845'}] but found [ContactData{id='2147483647', name='Hanna'}]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:831)
at org.testng.Assert.assertEquals(Assert.java:796)
at ru.stqa.pft.addressbook.test.NewContactCreation.testNewContactCreation(NewContactCreation.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
    </failure>
  </testcase> <!-- testNewContactCreation -->
</testsuite> <!-- ru.stqa.pft.addressbook.test.NewContactCreation -->
